name : this is the first Github action file

on : [push]

jobs : 
  build: 
    runs-on: self-hosted

    strategy:
      matrix :
        python-verison: [3.9]
    
    
    steps :
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-verison }}
    

      - name: Install Dependencies
        run : |
          python -m pip install --upgrade pip
          pip install pytest
      
      - name : Run testss
        run : |
          cd testing
          python -m pytest test.py